nfs:
  server: 192.168.56.11
  path: /srv/nfs_shares/kubernetes

storageClass:
  defaultClass: true
  name: nfs-client
  reclaimPolicy: Delete

image:
  repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2

replicaCount: 1